package io.pandora.mall.mapper.system;

import io.pandora.mall.base.BaseDao;
import io.pandora.mall.domian.system.RolePermission;

public interface RolePermissionMapper extends BaseDao<RolePermission> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_sys_role_permission
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    int insertSelective(RolePermission record);

}