package io.pandora.mall.domian.system;

import com.baomidou.mybatisplus.annotation.TableName;
import io.pandora.mall.base.BaseDo;

@TableName("mall_sys_dept_role")
public class DeptRole extends BaseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_dept_role.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_dept_role.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_dept_role.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_dept_role.id
     *
     * @return the value of mall_sys_dept_role.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_dept_role.id
     *
     * @param id the value for mall_sys_dept_role.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_dept_role.dept_id
     *
     * @return the value of mall_sys_dept_role.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_dept_role.dept_id
     *
     * @param deptId the value for mall_sys_dept_role.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_dept_role.role_id
     *
     * @return the value of mall_sys_dept_role.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_dept_role.role_id
     *
     * @param roleId the value for mall_sys_dept_role.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}