package io.pandora.mall.domian.system;

import com.baomidou.mybatisplus.annotation.TableName;
import io.pandora.mall.base.BaseDo;

import java.util.Date;

@TableName("mall_sys_menu")
public class Menu extends BaseDo {

    private Integer id;

    private Boolean iFrame;

    private String name;

    private String location;

    private Integer pid;

    private Integer sort;

    private String icon;

    private String url;

    private Boolean hidden;

    private String locationName;

    private Integer roleId;

    private Integer type;

    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.id
     *
     * @return the value of mall_sys_menu.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.id
     *
     * @param id the value for mall_sys_menu.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.i_frame
     *
     * @return the value of mall_sys_menu.i_frame
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Boolean getiFrame() {
        return iFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.i_frame
     *
     * @param iFrame the value for mall_sys_menu.i_frame
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setiFrame(Boolean iFrame) {
        this.iFrame = iFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.name
     *
     * @return the value of mall_sys_menu.name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.name
     *
     * @param name the value for mall_sys_menu.name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.location
     *
     * @return the value of mall_sys_menu.location
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.location
     *
     * @param location the value for mall_sys_menu.location
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.pid
     *
     * @return the value of mall_sys_menu.pid
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.pid
     *
     * @param pid the value for mall_sys_menu.pid
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.sort
     *
     * @return the value of mall_sys_menu.sort
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.sort
     *
     * @param sort the value for mall_sys_menu.sort
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.icon
     *
     * @return the value of mall_sys_menu.icon
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.icon
     *
     * @param icon the value for mall_sys_menu.icon
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.url
     *
     * @return the value of mall_sys_menu.url
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.url
     *
     * @param url the value for mall_sys_menu.url
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.hidden
     *
     * @return the value of mall_sys_menu.hidden
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Boolean getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.hidden
     *
     * @param hidden the value for mall_sys_menu.hidden
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.location_name
     *
     * @return the value of mall_sys_menu.location_name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.location_name
     *
     * @param locationName the value for mall_sys_menu.location_name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.role_id
     *
     * @return the value of mall_sys_menu.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.role_id
     *
     * @param roleId the value for mall_sys_menu.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.type
     *
     * @return the value of mall_sys_menu.type
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.type
     *
     * @param type the value for mall_sys_menu.type
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_menu.create_time
     *
     * @return the value of mall_sys_menu.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_menu.create_time
     *
     * @param createTime the value for mall_sys_menu.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}