package io.pandora.mall.domian.system;

import com.baomidou.mybatisplus.annotation.TableName;
import io.pandora.mall.base.BaseDo;

import java.util.Date;

@TableName("mall_sys_permission")
public class Permission extends BaseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_permission.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_permission.name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_permission.code
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_permission.status
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_permission.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_permission.id
     *
     * @return the value of mall_sys_permission.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_permission.id
     *
     * @param id the value for mall_sys_permission.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_permission.name
     *
     * @return the value of mall_sys_permission.name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_permission.name
     *
     * @param name the value for mall_sys_permission.name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_permission.code
     *
     * @return the value of mall_sys_permission.code
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_permission.code
     *
     * @param code the value for mall_sys_permission.code
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_permission.status
     *
     * @return the value of mall_sys_permission.status
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_permission.status
     *
     * @param status the value for mall_sys_permission.status
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_permission.create_time
     *
     * @return the value of mall_sys_permission.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_permission.create_time
     *
     * @param createTime the value for mall_sys_permission.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}