package io.pandora.mall.domian.system;

import com.baomidou.mybatisplus.annotation.TableName;
import io.pandora.mall.base.BaseDo;

@TableName("mall_sys_role_menu")
public class RoleMenu extends BaseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_role_menu.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_role_menu.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_role_menu.id
     *
     * @return the value of mall_sys_role_menu.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_role_menu.id
     *
     * @param id the value for mall_sys_role_menu.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_role_menu.role_id
     *
     * @return the value of mall_sys_role_menu.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_role_menu.role_id
     *
     * @param roleId the value for mall_sys_role_menu.role_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_role_menu.menu_id
     *
     * @return the value of mall_sys_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_role_menu.menu_id
     *
     * @param menuId the value for mall_sys_role_menu.menu_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}