package io.pandora.mall.domian.system;

import com.baomidou.mybatisplus.annotation.TableName;
import io.pandora.mall.base.BaseDo;

import java.util.Date;

@TableName("mall_sys_user")
public class User extends BaseDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.account
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.password
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.nick_name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.avatear
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String avatear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.email
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.job_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.sex
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_sys_user.update_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    private Date updateTime;

    private byte enable;

    public byte getEnable() {
        return enable;
    }

    public void setEnable(byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.id
     *
     * @return the value of mall_sys_user.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.id
     *
     * @param id the value for mall_sys_user.id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.account
     *
     * @return the value of mall_sys_user.account
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.account
     *
     * @param account the value for mall_sys_user.account
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.password
     *
     * @return the value of mall_sys_user.password
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.password
     *
     * @param password the value for mall_sys_user.password
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.nick_name
     *
     * @return the value of mall_sys_user.nick_name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.nick_name
     *
     * @param nickName the value for mall_sys_user.nick_name
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.avatear
     *
     * @return the value of mall_sys_user.avatear
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getAvatear() {
        return avatear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.avatear
     *
     * @param avatear the value for mall_sys_user.avatear
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setAvatear(String avatear) {
        this.avatear = avatear == null ? null : avatear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.email
     *
     * @return the value of mall_sys_user.email
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.email
     *
     * @param email the value for mall_sys_user.email
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.dept_id
     *
     * @return the value of mall_sys_user.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.dept_id
     *
     * @param deptId the value for mall_sys_user.dept_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.job_id
     *
     * @return the value of mall_sys_user.job_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.job_id
     *
     * @param jobId the value for mall_sys_user.job_id
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.sex
     *
     * @return the value of mall_sys_user.sex
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.sex
     *
     * @param sex the value for mall_sys_user.sex
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.create_time
     *
     * @return the value of mall_sys_user.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.create_time
     *
     * @param createTime the value for mall_sys_user.create_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_sys_user.update_time
     *
     * @return the value of mall_sys_user.update_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_sys_user.update_time
     *
     * @param updateTime the value for mall_sys_user.update_time
     *
     * @mbggenerated Wed Sep 09 16:19:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}