server:
  port: 9009
#  tomcat:
#    max-threads: 2000
#    min-spare-threads: 30
#    uri-encoding: UTF-8
  jetty:
    acceptors: 2
    selectors: 4

spring:
  profiles:
    active: dev
  application:
    name: pandora-mall
  banner:
    location: config/banner.txt

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: io.pandora.mall.**.domian
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

logging:
  path: logs/
  file: pandora.modelue
  config: classpath:config/logback-spring.xml

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#忽略token验证的接口
ignore:
  urls:
  - /api/**
  - /pay/**
  - /csrf
  - /v2/api-docs
  - /swagger-resources/**
  - /webjars/**
  - /robots.txt
  - /druid/**
  - /v1/user/login
  # 测试阶段放行
  - /manage/**
#  authenticates:
#  - /manage/**

